#!/bin/sh
#Script by Maze_31

#Requirements
apt update
apt upgrade -y

#openSSH-server
apt install openssh-server

#ssh config
nano /etc/ssh/sshd_config

#Enable SSH
systemctl enable ssh
systemctl start ssh
